### ISSUE TITLE
Allow font configuration

### ISSUE THREAD

**Issue by japgolly** [atom-haskell/haskell-ghc-mod#122]
The little console that shows errors, warnings, etc is pretty hard to read on my system. I'd like to make the font bigger, maybe chose a different one.

**Comment by lierdakil** [comment]
With ide-haskell 1.5.3, something like this in your stylesheet will work:

```less
ide-haskell-panel-item > * {
  font-size: 18pt !important;
  font-family: "Comic Sans MS" !important;
}
```
