### ISSUE TITLE
ghc-mod-5.5.0.0 not working with multi project stack.yaml

### ISSUE THREAD

**Issue by lippling** [atom-haskell/haskell-ghc-mod#136]
I've the following setup:
- `stack` with `lts-5.13`
- `ghc-mod-5.5.0.0` installed via `stack --resolver lts-5.13 build ghc-mod`

`stack.yaml:`
```yaml
resolver: lts-5.13

packages:
- oauth2/
- server/
- location:
    git: git@github.com:hotwirestudios/haskell-opaleye.git
    commit: ba708c17bd5aec4f1cc52f82bc61d7894bac6f48
- location:
    git: git@github.com:hotwirestudios/opaleye-trans.git
    commit: 39583daafac28575ec110f4ed162278133e9d770
```

When I open and save a `.hs` file in Atom, every package (which was installed by `stack`) is marked with "...could not be found..." after the `import`.
This seems only to be the case for multi project setups. When I run `atom .` directly in the subdirectory it works.

I tested several things (none worked):
- deleted `~/.ghc-mod`
- deleted `~/.stack`
- deleted `.stack-work`
- ...

Using `ghc-mod-5.4.0.0` seems to be a workaround:
- Remove `ghc-mod*` which was installed with `stack --resolver lts-5.13 build ghc-mod` (`~/.stack/snapshots/x86_64-osx/lts-5.13/7.10.3/bin/`).
- Run `stack --resolver lts-4.2 install ghc-mod`. This installs `ghc-mod 5.4.0.0` into the `~/.local/bin` folder.
